title: Robotics
author: "@ The George Washington University"
description: "Robotics"
url: "/robotics-course-materials"
baseurl: "/robotics-course-materials"
paginate_path: "blog/page:num/"
permalink: blog/:title/

#markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
paginate: 20

#navigation:
# - title: Home
#   url: /blog/index.html

social:
#   github: positronicslab
#   twitter: brianmaierjr
#   facebook: brianmaierjr
#   email: brimaidesigns@gmail.com

